title: Ji-Young Yang
description: PhD candidate in computational chemistry and drug discovery
url: https://jiyoungyang1.github.io
baseurl: /portfolio

author:
  name: Ji-Young Yang
  email: ji-young.yang@uni-ulm.de

markdown: kramdown
