# Site settings
title: Ji-Young Yang
email: jiyoung.jane.yang@gmail.com
description: >-
  PhD candidate specializing in molecular dynamics simulations,
  advanced spectroscopic data analysis, and AI-driven drug discovery

url: https://jiyoungyang1.github.io
baseurl: /portfolio

# Theme - Using GitHub Pages supported theme
theme: minima

# Plugins (GitHub Pages compatible only)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Author information
author:
  name: Ji-Young Yang
  email: jiyoung.jane.yang@gmail.com

# Social links
github_username: jiyoungyang1
linkedin_username: ji-young-y-28a828142

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - README.md
  - SETUP_GUIDE.md
  - QUICK_START.md
  - START_HERE.md
  - PROJECT_SUMMARY.md
  - FILE_STRUCTURE.md
  - THEME_OPTIONS.md
  - AL_FOLIO_SETUP.md
  - AGENTS.md
  - preview.html
